# Generated by Django 5.1.3 on 2025-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('bookswap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wishlist_books',
            field=models.ManyToManyField(related_name='wishlist_books', through='bookswap.WishList', to='bookswap.book'),
        ),
    ]
