# Generated by Django 5.2 on 2025-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
