# Generated by Django 5.2 on 2025-05-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0003_booklisting_created_at_booklisting_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='swap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswap.swap'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('member', 'book')},
        ),
    ]
