# Generated by Django 5.2 on 2025-05-15 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0004_alter_transaction_swap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=7, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
