# Generated by Django 5.2 on 2025-05-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0005_alter_book_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=7),
        ),
    ]
