# Generated by Django 5.2 on 2025-05-15 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0006_alter_book_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.TextField(default='No image'),
        ),
        migrations.AlterField(
            model_name='booklisting',
            name='member_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
