# Generated by Django 5.2 on 2025-05-21 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0009_my_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Library',
            new_name='LibraryItem',
        ),
        migrations.AlterUniqueTogether(
            name='libraryitem',
            unique_together=set(),
        ),
        # migrations.RemoveField(
        #     model_name='booklisting',
        #     name='book',
        # ),
        migrations.AddField(
            model_name='booklisting',
            name='library_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswap.libraryitem'),
        ),
    ]
