# Generated by Django 5.2 on 2025-05-20 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0009_my_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Library',
            new_name='LibraryItem',
        ),
    ]
