# Generated by Django 5.2 on 2025-05-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0010_rename_my_library_libraryitem'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='booklisting',
        #     name='book',
        # ),
        # migrations.AddField(
        #     model_name='booklisting',
        #     name='library_item',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookswap.libraryitem'),
        # ),
    ]
