# Generated by Django 5.2 on 2025-05-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0011_remove_booklisting_book_booklisting_library_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libraryitem',
            unique_together=set(),
        ),
    ]
