# Generated by Django 5.1.3 on 2025-05-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0012_alter_libraryitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklisting',
            name='book',
        ),
    ]
