# Generated by Django 5.2 on 2025-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0013_remove_booklisting_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
