# Generated by Django 5.2 on 2025-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0014_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
