# Generated by Django 5.2 on 2025-05-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0015_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.TextField(default='1st AVE East', max_length=255),
            preserve_default=False,
        ),
    ]
