# Generated by Django 5.2 on 2025-05-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0016_shipment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
