# Generated by Django 5.2 on 2025-05-22 22:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0017_booklisting_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
