# Generated by Django 5.2 on 2025-05-23 00:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0018_alter_booklisting_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('book_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswap.booklisting')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_detail_from_member', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswap.shipment')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_detail_to_member', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookswap.transaction')),
            ],
        ),
    ]
