# Generated by Django 5.2 on 2025-05-23 00:50

from django.db import migrations



def populate_transaction_details_from_existing_transactions(apps, schema_editor):
    Transaction = apps.get_model('bookswap', 'Transaction')
    TransactionDetail = apps.get_model('bookswap', 'TransactionDetail')
    all_transactions = Transaction.objects.all()
    for transaction in all_transactions:
        detail = TransactionDetail(
            transaction=transaction,
            book_listing=transaction.book_listing,
            from_member=transaction.from_member,
            to_member=transaction.to_member,
            shipment=transaction.shipment,
            cost=transaction.cost
        )
        detail.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0019_transactiondetail'),
    ]

    operations = [
        migrations.RunPython(populate_transaction_details_from_existing_transactions),
    ]
