# Generated by Django 5.2 on 2025-05-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0020_populate_transaction_detials_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='swap',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='from_member',
            new_name='initiator_member',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_member',
            new_name='receiver_member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='book_listing',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Swap',
        ),
    ]
