# Generated by Django 5.2 on 2025-05-23 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0021_remove_transaction_swap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='initiator_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='bookswap.transaction'),
        ),
    ]
